name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.11.0
          arch: win64_msvc2022_64

      - name: Configure
        shell: pwsh
        run: |
          cmake -B build `
            -G "Visual Studio 17 2022" `
            -A x64

      - name: Build
        run: cmake --build build --config Release

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: atem-emulator
          path: |
            build/Release/*.exe
            build/Release/*.dll
